# idiomas.py

TRADUCCIONES = {
    'es_ES': {
        'titulo': "Prover9-Mace4 GUI",
        'menu_archivo': "&Archivo",
        'accion_nuevo': "Nuevo Proyecto",
        'accion_abrir': "&Abrir Archivo (.in)...",
        'accion_guardar': "&Guardar",
        'accion_exportar': "&Exportar Salida (.out)...",
        'accion_salir': "&Salir",
        'tab_p9': "Demostrador Prover9",
        'tab_m4': "Buscador de Modelos Mace4",
        'chk_modo_avanzado': "Modo Avanzado (Editor de código libre)",
        'lbl_premisas_p9': "Premisas / Hipótesis (una por línea, sin 'formulas(sos).' ni puntos):",
        'lbl_conclusion_p9': "Teorema / Conclusión a demostrar (sin 'formulas(goals).' ni puntos):",
        'lbl_libre_p9': "Editor libre Prover9 (Código completo):",
        'btn_verificar_p9': "Verificar Deducción (Prover9)",
        'lbl_resultado': "Resultado del Análisis:",
        'lbl_premisas_m4': "Premisas / Hipótesis (una por línea, sin código):",
        'lbl_objetivo_m4': "Objetivo que sospechas falso (sin código):",
        'lbl_libre_m4': "Editor libre Mace4 (Código completo):",
        'btn_buscar_m4': "Buscar Contraejemplo (Mace4)",
        'grupo_insercion': "Inserción Rápida",
        'lbl_operadores': "Operadores lógicos:",
        'msg_procesando_p9': "Prover9 está procesando las cláusulas...",
        'msg_procesando_m4': "Mace4 está buscando un contraejemplo finito...",
        'menu_idioma': "&Idioma",
        'op_neg': "Negación ( - )",
        'op_conj': "Conjunción ( && )",
        'op_disj': "Disyunción ( | )",
        'op_impl': "Implicación ( -> )",
        'op_equiv': "Equivalencia ( <-> )",
        'ph_premisas_p9': "Ejemplo:\np -> q\np",
        'ph_conclusion_p9': "Ejemplo:\nq",
        'ph_libre_p9': "Ejemplo:\nformulas(sos).\n  p -> q.\n  p.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        'ph_premisas_m4': "Ejemplo:\np -> q",
        'ph_conclusion_m4': "Ejemplo:\nq",
        'ph_libre_m4': "Ejemplo:\nformulas(sos).\n  p -> q.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        
        # NUEVO MENÚ DE EJEMPLOS (Español)
        'menu_ejemplos': "&Ejemplos",
        'ej_p9_1': "Silogismo Clásico (Modus Ponens)",
        'ej_p9_2': "Dilema Constructivo",
        'ej_m4_1': "Teoría de Grupos (Buscar Orden)",
        'ej_m4_2': "No-Conmutatividad (Contraejemplo)",
        'ej_p9_3': "Álgebra: Grupo Booleano",
        'ej_m4_3': "Axiomas: Retículo No Distributivo",
        
        # Contenidos de los ejemplos
        'datos_silogismo_premisas': "todos_los_hombres_son_mortales -> aristoteles_es_mortal\ntodos_los_hombres_son_mortales",
        'datos_silogismo_conclusion': "aristoteles_es_mortal",
        'datos_paradoja_premisas': "(p -> q) & (r -> s)\np | r",
        'datos_paradoja_conclusion': "q | s" ,
        'datos_algebra_premisas': "f(e, x) = x.\nf(g(x), x) = e.\nf(f(x, y), z) = f(x, f(y, z)).\n\n% Propiedad del Grupo Booleano\nf(x, x) = e.",
        'datos_algebra_conclusion': "f(x, y) = f(y, x).",

        'datos_grupo_premisas': "f(x,e) = x\nf(e,x) = x\n f(x,g(x)) = e\nf(g(x),x) = e\nf(f(x,y),z) = f(x,f(y,z))",
        'datos_grupo_conclusion': "", # Dejar vacío para que Mace4 busque modelos generales de la teoría
        'datos_conmut_premisas': "f(x,e) = x\nf(e,x) = x\nf(f(x,y),z) = f(x,f(y,z))",
        'datos_conmut_conclusion': "f(x,y) = f(y,x)", # Buscaremos un contraejemplo donde no se cumpla
        'datos_reticulo_premisas': "% Axiomas de un retículo (Lattice)\nv(x,y) = v(y,x).\nn(x,y) = n(y,x).\nv(x, v(y,z)) = v(v(x,y), z).\nn(x, n(y,z)) = n(n(x,y), z).\nv(x, n(x,y)) = x.\nn(x, v(x,y)) = x.",
        'datos_reticulo_conclusion': "% Ley distributiva (Mace4 generará un contraejemplo)\nv(x, n(y,z)) = n(v(x,y), v(x,z)).",

        'tit_historial': "Historial de Ejecuciones",
        'col_hora': "Hora",
        'col_motor': "Motor",
        'col_resultado': "Resultado",
        'status_sin_archivo': "Sin archivo abierto",
        'status_guardado': "Archivo guardado: ",
        'status_error_guardar': "Error al guardar el archivo",
        'status_abierto': "Archivo abierto: ",
        'hist_proved': "Demostrado",
        'hist_no_proved': "No demostrado",
        'hist_counter': "Contraejemplo",
        'hist_no_counter': "Sin contraejemplo",
        'hist_timeout': "Tiempo agotado",
        'hist_error': "Error sintaxis/entorno",

        # NUEVOS TEXTOS: Configuración de Timeout (Español)
        'menu_config': "&Configuración",
        'lbl_timeout': "Tiempo límite (seg):"
    },
    'en_US': {
        'titulo': "Prover9-Mace4 GUI",
        'menu_archivo': "&File",
        'accion_nuevo': "New Project",
        'accion_abrir': "&Open File (.in)...",
        'accion_guardar': "&Save",
        'accion_exportar': "&Export Output (.out)...",
        'accion_salir': "&Exit",
        'tab_p9': "Prover9 Theorem Prover",
        'tab_m4': "Mace4 Model Finder",
        'chk_modo_avanzado': "Advanced Mode (Free code editor)",
        'lbl_premisas_p9': "Premises / Hypotheses (one per line, without 'formulas(sos).' or periods):",
        'lbl_conclusion_p9': "Theorem / Conclusion to prove (without 'formulas(goals).' or periods):",
        'lbl_libre_p9': "Prover9 free editor (Full code):",
        'btn_verificar_p9': "Verify Deduction (Prover9)",
        'lbl_resultado': "Analysis Result:",
        'lbl_premisas_m4': "Premises / Hypotheses (one per line, without code):",
        'lbl_objetivo_m4': "Goal suspected to be false (without code):",
        'lbl_libre_m4': "Mace4 free editor (Full code):",
        'btn_buscar_m4': "Search Counterexample (Mace4)",
        'grupo_insercion': "Quick Insert",
        'lbl_operadores': "Logical operators:",
        'msg_procesando_p9': "Prover9 is processing the clauses...",
        'msg_procesando_m4': "Mace4 is searching for a finite counterexample...",
        'menu_idioma': "&Language",
        'op_neg': "Negation ( - )",
        'op_conj': "Conjunction ( && )",
        'op_disj': "Disjunction ( | )",
        'op_impl': "Implication ( -> )",
        'op_equiv': "Equivalence ( <-> )",
        'ph_premisas_p9': "Example:\np -> q\np",
        'ph_conclusion_p9': "Example:\nq",
        'ph_libre_p9': "Example:\nformulas(sos).\n  p -> q.\n  p.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        'ph_premisas_m4': "Example:\np -> q",
        'ph_conclusion_m4': "Example:\nq",
        'ph_libre_m4': "Example:\nformulas(sos).\n  p -> q.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        
        # NUEVO MENÚ DE EJEMPLOS (Inglés)
        'menu_ejemplos': "&Examples",
        'ej_p9_1': "Classical Syllogism (Modus Ponens)",
        'ej_p9_2': "Constructive Dilemma",
        'ej_m4_1': "Group Theory (Search Models)",
        'ej_m4_2': "Non-Commutativity (Counterexample)",
        'ej_p9_3': "Algebra: Boolean Group",
        'ej_m4_3': "Axioms: Non-Distributive Lattice",
        
        # Contenidos (los mantenemos iguales porque la lógica formal es universal, ¡como mi planta!)
        'datos_silogismo_premisas': "all_men_are_mortal -> aristotle_is_mortal\nall_men_are_mortal",
        'datos_silogismo_conclusion': "aristotle_is_mortal",
        'datos_paradoja_premisas': "(p -> q) & (r -> s)\np | r",
        'datos_paradoja_conclusion': "q | s",
        'datos_algebra_premisas': "f(e, x) = x.\nf(g(x), x) = e.\nf(f(x, y), z) = f(x, f(y, z)).\n\n% Boolean Group Property\nf(x, x) = e.",
        'datos_algebra_conclusion': "f(x, y) = f(y, x).",

        'datos_grupo_premisas': "f(x,e) = x\nf(e,x) = x\nf(x,g(x)) = e\nf(g(x),x) = e\nf(f(x,y),z) = f(x,f(y,z))",
        'datos_grupo_conclusion': "",
        'datos_conmut_premisas': "f(x,e) = x\nf(e,x) = x\nf(f(x,y),z) = f(x,f(y,z))",
        'datos_conmut_conclusion': "f(x,y) = f(y,x)",
        'datos_reticulo_premisas': "% Lattice Axioms\nv(x,y) = v(y,x).\nn(x,y) = n(y,x).\nv(x, v(y,z)) = v(v(x,y), z).\nn(x, n(y,z)) = n(n(x,y), z).\nv(x, n(x,y)) = x.\nn(x, v(x,y)) = x.",
        'datos_reticulo_conclusion': "% Distributive law (Mace4 will find a countermodel)\nv(x, n(y,z)) = n(v(x,y), v(x,z)).",

        'tit_historial': "Execution History",
        'col_hora': "Time",
        'col_motor': "Engine",
        'col_resultado': "Result",
        'status_sin_archivo': "No open file",
        'status_guardado': "File saved: ",
        'status_error_guardar': "Error saving file",
        'status_abierto': "File opened: ",
        'hist_proved': "Proved",
        'hist_no_proved': "Not proved",
        'hist_counter': "Counterexample",
        'hist_no_counter': "No counterexample",
        'hist_timeout': "Timeout",
        'hist_error': "Syntax/Env Error",

        # NUEVOS TEXTOS: Configuración de Timeout (Inglés)
        'menu_config': "&Settings",
        'lbl_timeout': "Timeout limit (sec):"
    }
}

DICCIONARIO_PANELES = {
    'es_ES': {
        'Basic Options': 'Opciones Básicas', 'All Options': 'Todas las Opciones',
        'Other Options': 'Otras Opciones', 'Experimental Options': 'Opciones Experimentales',
        'Reset These to Defaults': 'Restablecer por defecto',
        'Meta Options': 'Opciones Meta', 'Term Ordering': 'Orden de Términos',
        'Limits': 'Límites', 'Search Prep': 'Prep. de Búsqueda',
        'Goals/Denials': 'Objetivos/Negaciones', 'Select Given': 'Selección de Dados',
        'Inference Rules': 'Reglas de Inferencia', 'Rewriting': 'Reescritura',
        'Weighting': 'Pesos', 'Process Inferred': 'Proceso Inferido',
        'Input/Output': 'Entrada/Salida', 'Hints': 'Pistas',
        'Search Limits': 'Límites de Búsqueda', 'Limits on Kept Clauses': 'Límites de Cláusulas',
        'Sos Control': 'Control SOS', 'Selection Ratio': 'Ratio de Selección',
        'Semantic Guidance': 'Guía Semántica', 'Others': 'Otros',
        'Ordinary Rules': 'Reglas Ordinarias', 'Other Rules': 'Otras Reglas',
        'General Restrictions': 'Restricciones Generales', 'Resolution Restrictions': 'Restr. de Resolución',
        'Paramodulation Restrictions': 'Restr. de Paramodulación', 'Term Rewriting Limits': 'Límites de Reescritura',
        'Lex-Dependent Rewriting': 'Reescritura Dependiente Lex', 'Symbol Weights': 'Pesos de Símbolos',
        'Penalties': 'Penalizaciones',
        'none': 'ninguno', 'some': 'algunos', 'lots': 'muchos', 'all': 'todos',
        'false_in_all': 'falso_en_todas', 'false_in_some': 'falso_en_algunas',
        'evens': 'pares', 'odds': 'impares', 'primes': 'primos', 'nonprimes': 'no_primos'
    }
}