# idiomas.py

TRADUCCIONES = {
    'es_ES': {
        'titulo': "Prover9-Mace4 GUI",
        'menu_archivo': "&Archivo",
        'accion_nuevo': "Nuevo Proyecto",
        'accion_abrir': "&Abrir Archivo (.in)...",
        'accion_guardar': "&Guardar",
        'accion_exportar': "&Exportar Salida (.out)...",
        'accion_salir': "&Salir",
        'tab_p9': "Demostrador Prover9",
        'tab_m4': "Buscador de Modelos Mace4",
        'chk_modo_avanzado': "Modo Avanzado (Editor de código libre)",
        'lbl_premisas_p9': "Premisas / Hipótesis (una por línea, sin 'formulas(sos).' ni puntos):",
        'lbl_conclusion_p9': "Teorema / Conclusión a demostrar (sin 'formulas(goals).' ni puntos):",
        'lbl_libre_p9': "Editor libre Prover9 (Código completo):",
        'btn_verificar_p9': "Verificar Deducción (Prover9)",
        'lbl_resultado': "Resultado del Análisis:",
        'lbl_premisas_m4': "Premisas / Hipótesis (una por línea, sin código):",
        'lbl_objetivo_m4': "Objetivo que sospechas falso (sin código):",
        'lbl_libre_m4': "Editor libre Mace4 (Código completo):",
        'btn_buscar_m4': "Buscar Contraejemplo (Mace4)",
        'grupo_insercion': "Inserción Rápida",
        'lbl_operadores': "Operadores lógicos:",
        'msg_procesando_p9': "Prover9 está procesando las cláusulas...",
        'msg_procesando_m4': "Mace4 está buscando un contraejemplo finito...",
        'menu_idioma': "&Idioma",
        'op_neg': "Negación ( - )",
        'op_conj': "Conjunción ( && )",
        'op_disj': "Disyunción ( | )",
        'op_impl': "Implicación ( -> )",
        'op_equiv': "Equivalencia ( <-> )",
        'ph_premisas_p9': "Ejemplo:\np -> q\np",
        'ph_conclusion_p9': "Ejemplo:\nq",
        'ph_libre_p9': "Ejemplo:\nformulas(sos).\n  p -> q.\n  p.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        'ph_premisas_m4': "Ejemplo:\np -> q",
        'ph_conclusion_m4': "Ejemplo:\nq",
        'ph_libre_m4': "Ejemplo:\nformulas(sos).\n  p -> q.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        
        # NUEVO MENÚ DE EJEMPLOS (Español)
        'menu_ejemplos': "&Ejemplos",
        'ej_silogismo': "Silogismo Clásico (Modus Ponens)",
        'ej_paradoja': "Dilema Constructivo",
        
        # Contenidos de los ejemplos
        'datos_silogismo_premisas': "todos_los_hombres_son_mortales -> aristoteles_es_mortal\ntodos_los_hombres_son_mortales",
        'datos_silogismo_conclusion': "aristoteles_es_mortal",
        'datos_paradoja_premisas': "(p -> q) & (r -> s)\np | r",
        'datos_paradoja_conclusion': "q | s"
    },
    'en_US': {
        'titulo': "Prover9-Mace4 GUI",
        'menu_archivo': "&File",
        'accion_nuevo': "New Project",
        'accion_abrir': "&Open File (.in)...",
        'accion_guardar': "&Save",
        'accion_exportar': "&Export Output (.out)...",
        'accion_salir': "&Exit",
        'tab_p9': "Prover9 Theorem Prover",
        'tab_m4': "Mace4 Model Finder",
        'chk_modo_avanzado': "Advanced Mode (Free code editor)",
        'lbl_premisas_p9': "Premises / Hypotheses (one per line, without 'formulas(sos).' or periods):",
        'lbl_conclusion_p9': "Theorem / Conclusion to prove (without 'formulas(goals).' or periods):",
        'lbl_libre_p9': "Prover9 free editor (Full code):",
        'btn_verificar_p9': "Verify Deduction (Prover9)",
        'lbl_resultado': "Analysis Result:",
        'lbl_premisas_m4': "Premises / Hypotheses (one per line, without code):",
        'lbl_objetivo_m4': "Goal suspected to be false (without code):",
        'lbl_libre_m4': "Mace4 free editor (Full code):",
        'btn_buscar_m4': "Search Counterexample (Mace4)",
        'grupo_insercion': "Quick Insert",
        'lbl_operadores': "Logical operators:",
        'msg_procesando_p9': "Prover9 is processing the clauses...",
        'msg_procesando_m4': "Mace4 is searching for a finite counterexample...",
        'menu_idioma': "&Language",
        'op_neg': "Negation ( - )",
        'op_conj': "Conjunction ( && )",
        'op_disj': "Disjunction ( | )",
        'op_impl': "Implication ( -> )",
        'op_equiv': "Equivalence ( <-> )",
        'ph_premisas_p9': "Example:\np -> q\np",
        'ph_conclusion_p9': "Example:\nq",
        'ph_libre_p9': "Example:\nformulas(sos).\n  p -> q.\n  p.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        'ph_premisas_m4': "Example:\np -> q",
        'ph_conclusion_m4': "Example:\nq",
        'ph_libre_m4': "Example:\nformulas(sos).\n  p -> q.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        
        # NUEVO MENÚ DE EJEMPLOS (Inglés)
        'menu_ejemplos': "&Examples",
        'ej_silogismo': "Classical Silogism (Modus Ponens)",
        'ej_paradoja': "Constructive Dilemma",
        
        # Contenidos (los mantenemos iguales porque la lógica formal es universal, ¡como mi planta!)
        'datos_silogismo_premisas': "all_men_are_mortal -> aristotle_is_mortal\nall_men_are_mortal",
        'datos_silogismo_conclusion': "aristotle_is_mortal",
        'datos_paradoja_premisas': "(p -> q) & (r -> s)\np | r",
        'datos_paradoja_conclusion': "q | s"
    }
}