"""
@file idiomas.py
@brief Diccionarios de internacionalización y traducción para la interfaz gráfica.

Contiene las bases de datos locales para permitir el cambio dinámico de idioma 
entre Español (es_ES) e Inglés (en_US) en toda la aplicación.
"""

##
# @brief Diccionario principal con los textos estáticos de la interfaz en múltiples idiomas.
# 
# Almacena las traducciones para la barra de menús, pestañas, botones, 
# placeholders, historial de ejecuciones y problemas de ejemplo predefinidos.
# Las claves utilizan un formato de variable abstracta (ej. 'btn_verificar_p9').
TRADUCCIONES = {
    'es_ES': {
        'titulo': "Prover9-Mace4 GUI",
        'menu_archivo': "&Archivo",
        'accion_nuevo': "Nuevo Proyecto",
        'accion_abrir': "&Abrir Archivo (.in)...",
        'accion_guardar': "&Guardar",
        'accion_exportar': "&Exportar Salida (.out)...",
        'accion_salir': "&Salir",
        'tab_p9': "Demostrador Prover9",
        'tab_m4': "Buscador de Modelos Mace4",
        'chk_modo_avanzado': "Modo Avanzado (Editor de código libre)",
        'lbl_premisas_p9': "Premisas / Hipótesis (una por línea, sin 'formulas(sos).' ni puntos):",
        'lbl_conclusion_p9': "Teorema / Conclusión a demostrar (sin 'formulas(goals).' ni puntos):",
        'lbl_libre_p9': "Editor libre Prover9 (Código completo):",
        'btn_verificar_p9': "Verificar Deducción (Prover9)",
        'lbl_resultado': "Resultado del Análisis:",
        'lbl_premisas_m4': "Premisas / Hipótesis (una por línea, sin 'formulas(sos).' ni puntos):",
        'lbl_objetivo_m4': "Objetivo que sospechas falso (sin 'formulas(goals).' ni puntos):",
        'lbl_libre_m4': "Editor libre Mace4 (Código completo):",
        'btn_buscar_m4': "Buscar Contraejemplo (Mace4)",
        'grupo_insercion': "Inserción Rápida",
        'lbl_operadores': "Operadores lógicos:",
        'msg_procesando_p9': "Prover9 está procesando las cláusulas...",
        'msg_procesando_m4': "Mace4 está buscando un contraejemplo finito...",
        'menu_idioma': "&Idioma",
        'op_neg': "Negación ( - )",
        'op_conj': "Conjunción ( && )",
        'op_disj': "Disyunción ( | )",
        'op_impl': "Implicación ( -> )",
        'op_equiv': "Equivalencia ( <-> )",
        'ph_premisas_p9': "Ejemplo:\np -> q\np",
        'ph_conclusion_p9': "Ejemplo:\nq",
        'ph_libre_p9': "Ejemplo:\nformulas(sos).\n  p -> q.\n  p.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        'ph_premisas_m4': "Ejemplo:\np -> q",
        'ph_conclusion_m4': "Ejemplo:\nq",
        'ph_libre_m4': "Ejemplo:\nformulas(sos).\n  p -> q.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        'menu_ejemplos': "&Ejemplos",
        'ej_p9_1': "1. Silogismo Clásico (Modus Ponens)",
        'datos_silogismo_premisas': "% Regla de implicación\np -> q.\n% Hecho conocido\np.",
        'datos_silogismo_conclusion': "% Conclusión esperada\nq.",
        'ej_p9_2': "2. Dilema Constructivo",
        'datos_paradoja_premisas': "% Implicaciones del dilema\np -> q.\nr -> s.\n% Disyunción de las premisas\np | r.",
        'datos_paradoja_conclusion': "% Disyunción de las conclusiones\nq | s.",
        'ej_p9_3': "3. Álgebra: Grupo Booleano",
        'datos_algebra_premisas': "% Axiomas de grupo\nf(e, x) = x.\nf(g(x), x) = e.\nf(f(x, y), z) = f(x, f(y, z)).\n\n% Propiedad del Grupo Booleano\nf(x, x) = e.",
        'datos_algebra_conclusion': "% Demostrar que es conmutativo\nf(x, y) = f(y, x).",
        'ej_m4_1': "1. Teoría de Grupos (Buscar orden)",
        'datos_grupo_premisas': "% Axiomas básicos de la teoría de grupos\nf(e, x) = x.\nf(x, e) = x.\nf(g(x), x) = e.\nf(x, g(x)) = e.\nf(f(x, y), z) = f(x, f(y, z)).",
        'datos_grupo_conclusion': "% Sin conclusión explícita\n% Mace4 buscará modelos que cumplan los axiomas anteriores",
        'ej_m4_2': "2. No-Conmutatividad (Contraejemplo)",
        'datos_conmut_premisas': "% Axioma de asociatividad\nf(f(x, y), z) = f(x, f(y, z)).",
        'datos_conmut_conclusion': "% Ley conmutativa\n% Mace4 generará un contraejemplo no conmutativo\nf(x, y) = f(y, x).",
        'ej_m4_3': "3. Axiomas: Retículo No Distributivo",
        'datos_reticulo_premisas': "% Axiomas de un retículo (Lattice)\nv(x,y) = v(y,x).\nn(x,y) = n(y,x).\nv(x, v(y,z)) = v(v(x,y), z).\nn(x, n(y,z)) = n(n(x,y), z).\nv(x, n(x,y)) = x.\nn(x, v(x,y)) = x.",
        'datos_reticulo_conclusion': "% Ley distributiva\n% Mace4 generará un contraejemplo\nv(x, n(y,z)) = n(v(x,y), v(x,z)).",
        'tit_historial': "Historial de Ejecuciones",
        'col_hora': "Hora",
        'col_motor': "Motor",
        'col_resultado': "Resultado",
        'status_sin_archivo': "Sin archivo abierto",
        'status_guardado': "Archivo guardado: ",
        'status_error_guardar': "Error al guardar el archivo",
        'status_abierto': "Archivo abierto: ",
        'hist_proved': "Demostrado",
        'hist_no_proved': "No demostrado",
        'hist_counter': "Contraejemplo",
        'hist_no_counter': "Sin contraejemplo",
        'hist_timeout': "Tiempo agotado",
        'hist_error': "Error sintaxis/entorno",
        'menu_config': "&Configuración",
        'lbl_timeout': "Tiempo límite (seg):"
    },
    'en_US': {
        'titulo': "Prover9-Mace4 GUI",
        'menu_archivo': "&File",
        'accion_nuevo': "New Project",
        'accion_abrir': "&Open File (.in)...",
        'accion_guardar': "&Save",
        'accion_exportar': "&Export Output (.out)...",
        'accion_salir': "&Exit",
        'tab_p9': "Prover9 Theorem Prover",
        'tab_m4': "Mace4 Model Finder",
        'chk_modo_avanzado': "Advanced Mode (Free code editor)",
        'lbl_premisas_p9': "Premises / Hypotheses (one per line, no 'formulas(sos).' or dots):",
        'lbl_conclusion_p9': "Theorem / Conclusion to prove (no 'formulas(goals).' or dots):",
        'lbl_libre_p9': "Prover9 free editor (Full code):",
        'btn_verificar_p9': "Verify Deduction (Prover9)",
        'lbl_resultado': "Analysis Result:",
        'lbl_premisas_m4': "Premises / Hypotheses (one per line, no 'formulas(sos).' or dots):",
        'lbl_objetivo_m4': "Goal suspected to be false (no 'formulas(goals).' or dots):",
        'lbl_libre_m4': "Mace4 free editor (Full code):",
        'btn_buscar_m4': "Search Counterexample (Mace4)",
        'grupo_insercion': "Quick Insert",
        'lbl_operadores': "Logical operators:",
        'msg_procesando_p9': "Prover9 is processing the clauses...",
        'msg_procesando_m4': "Mace4 is searching for a finite counterexample...",
        'menu_idioma': "&Language",
        'op_neg': "Negation ( - )",
        'op_conj': "Conjunction ( && )",
        'op_disj': "Disjunction ( | )",
        'op_impl': "Implication ( -> )",
        'op_equiv': "Equivalence ( <-> )",
        'ph_premisas_p9': "Example:\np -> q\np",
        'ph_conclusion_p9': "Example:\nq",
        'ph_libre_p9': "Example:\nformulas(sos).\n  p -> q.\n  p.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        'ph_premisas_m4': "Example:\np -> q",
        'ph_conclusion_m4': "Example:\nq",
        'ph_libre_m4': "Example:\nformulas(sos).\n  p -> q.\nend_of_list.\n\nformulas(goals).\n  q.\nend_of_list.",
        'menu_ejemplos': "&Examples",
        'ej_p9_1': "1. Classical Syllogism (Modus Ponens)",
        'datos_silogismo_premisas': "% Implication rule\np -> q.\n% Known fact\np.",
        'datos_silogismo_conclusion': "% Expected conclusion\nq.",
        'ej_p9_2': "2. Constructive Dilemma",
        'datos_paradoja_premisas': "% Dilemma implications\np -> q.\nr -> s.\n% Disjunction of premises\np | r.",
        'datos_paradoja_conclusion': "% Disjunction of conclusions\nq | s.",
        'ej_p9_3': "3. Algebra: Boolean Group",
        'datos_algebra_premisas': "% Group axioms\nf(e, x) = x.\nf(g(x), x) = e.\nf(f(x, y), z) = f(x, f(y, z)).\n\n% Boolean Group Property\nf(x, x) = e.",
        'datos_algebra_conclusion': "% Prove it is commutative\nf(x, y) = f(y, x).",
        'ej_m4_1': "1. Group Theory (Find order)",
        'datos_grupo_premisas': "% Basic axioms of group theory\nf(e, x) = x.\nf(x, e) = x.\nf(g(x), x) = e.\nf(x, g(x)) = e.\nf(f(x, y), z) = f(x, f(y, z)).",
        'datos_grupo_conclusion': "% No explicit conclusion\n% Mace4 will search for models satisfying the axioms",
        'ej_m4_2': "2. Non-Commutativity (Counterexample)",
        'datos_conmut_premisas': "% Associativity axiom\nf(f(x, y), z) = f(x, f(y, z)).",
        'datos_conmut_conclusion': "% Commutative law\n% Mace4 will generate a non-commutative counterexample\nf(x, y) = f(y, x).",
        'ej_m4_3': "3. Axioms: Non-Distributive Lattice",
        'datos_reticulo_premisas': "% Lattice axioms\nv(x,y) = v(y,x).\nn(x,y) = n(y,x).\nv(x, v(y,z)) = v(v(x,y), z).\nn(x, n(y,z)) = n(n(x,y), z).\nv(x, n(x,y)) = x.\nn(x, v(x,y)) = x.",
        'datos_reticulo_conclusion': "% Distributive law\n% Mace4 will find a countermodel\nv(x, n(y,z)) = n(v(x,y), v(x,z)).",
        'tit_historial': "Execution History",
        'col_hora': "Time",
        'col_motor': "Engine",
        'col_resultado': "Result",
        'status_sin_archivo': "No open file",
        'status_guardado': "File saved: ",
        'status_error_guardar': "Error saving file",
        'status_abierto': "File opened: ",
        'hist_proved': "Proved",
        'hist_no_proved': "Not proved",
        'hist_counter': "Counterexample",
        'hist_no_counter': "No counterexample",
        'hist_timeout': "Timeout",
        'hist_error': "Syntax/Env Error",
        'menu_config': "&Settings",
        'lbl_timeout': "Timeout limit (sec):"
    }
}


##
# @brief Diccionario para la traducción en vivo de los paneles de opciones avanzadas.
# 
# A diferencia de TRADUCCIONES, aquí las claves deben corresponder obligatoriamente 
# a los comandos literales esperados por los binarios (por ejemplo, 'lpo' o 'unfold').
DICCIONARIO_PANELES = {
    'es_ES': {
        'Basic Options': "Opciones Básicas",
        'All Options': "Todas las Opciones",
        'Other Options': "Otras Opciones",
        'Experimental Options': "Opciones Experimentales",
        'Reset These to Defaults': "Restablecer por defecto",
        'Meta Options': "Opciones Meta",
        'Term Ordering': "Orden de Términos",
        'Limits': "Límites",
        'Search Prep': "Prep. de Búsqueda",
        'Goals/Denials': "Objetivos/Negaciones",
        'Select Given': "Selección de Dados",
        'Inference Rules': "Reglas de Inferencia",
        'Rewriting': "Reescritura",
        'Weighting': "Pesos",
        'Process Inferred': "Proceso Inferido",
        'Input/Output': "Entrada/Salida",
        'Hints': "Pistas",
        'Search Limits': "Límites de Búsqueda",
        'Limits on Kept Clauses': "Límites de Cláusulas",
        'Sos Control': "Control SOS",
        'Selection Ratio': "Ratio de Selección",
        'Semantic Guidance': "Guía Semántica",
        'Others': "Otros",
        'Ordinary Rules': "Reglas Ordinarias",
        'Other Rules': "Otras Reglas",
        'General Restrictions': "Restricciones Generales",
        'Resolution Restrictions': "Restr. de Resolución",
        'Paramodulation Restrictions': "Restr. de Paramodulación",
        'Term Rewriting Limits': "Límites de Reescritura",
        'Lex-Dependent Rewriting': "Reescritura Dependiente Lex",
        'Symbol Weights': "Pesos de Símbolos",
        'Penalties': "Penalizaciones",
        'none': "ninguno",
        'some': "algunos",
        'lots': "muchos",
        'all': "todos",
        'false_in_all': "falso_en_todas",
        'false_in_some': "falso_en_algunas",
        'evens': "pares",
        'odds': "impares",
        'primes': "primos",
        'nonprimes': "no_primos"
    },
    'en_US': {
        'Basic Options': "Basic Options",
        'All Options': "All Options",
        'Other Options': "Other Options",
        'Experimental Options': "Experimental Options",
        'Reset These to Defaults': "Reset These to Defaults",
        'Meta Options': "Meta Options",
        'Term Ordering': "Term Ordering",
        'Limits': "Limits",
        'Search Prep': "Search Prep",
        'Goals/Denials': "Goals/Denials",
        'Select Given': "Select Given",
        'Inference Rules': "Inference Rules",
        'Rewriting': "Rewriting",
        'Weighting': "Weighting",
        'Process Inferred': "Process Inferred",
        'Input/Output': "Input/Output",
        'Hints': "Hints",
        'Search Limits': "Search Limits",
        'Limits on Kept Clauses': "Limits on Kept Clauses",
        'Sos Control': "Sos Control",
        'Selection Ratio': "Selection Ratio",
        'Semantic Guidance': "Semantic Guidance",
        'Others': "Others",
        'Ordinary Rules': "Ordinary Rules",
        'Other Rules': "Other Rules",
        'General Restrictions': "General Restrictions",
        'Resolution Restrictions': "Resolution Restrictions",
        'Paramodulation Restrictions': "Paramodulation Restrictions",
        'Term Rewriting Limits': "Term Rewriting Limits",
        'Lex-Dependent Rewriting': "Lex-Dependent Rewriting",
        'Symbol Weights': "Symbol Weights",
        'Penalties': "Penalties",
        'none': "none",
        'some': "some",
        'lots': "lots",
        'all': "all",
        'false_in_all': "false_in_all",
        'false_in_some': "false_in_some",
        'evens': "evens",
        'odds': "odds",
        'primes': "primes",
        'nonprimes': "nonprimes"
    }
}


##
# @brief Esquema estructural de las opciones avanzadas de Prover9.
# 
# Define la jerarquía de pestañas, categorías y widgets (spinboxes, comboboxes, 
# checkboxes) y sus valores por defecto. La GUI lee esta lista para auto-construirse.
SCHEMA_PROVER9 = [
    ("Meta Options", [
        ('flag', 'auto', True), ('flag', 'auto_setup', True), ('flag', 'auto_limits', True),
        ('flag', 'auto_denials', True), ('flag', 'auto_inference', True), ('flag', 'auto_process', True),
        ('flag', 'auto2', False), ('flag', 'raw', False)
    ]),
    ("Term Ordering", [
        ('combo', 'order', ["lpo", "rpo", "kbo"], "lpo"),
        ('combo', 'eq_defs', ["unfold", "fold", "pass"], "unfold"),
        ('flag', 'inverse_order', True)
    ]),
    ("Limits", [
        ('sub', 'Search Limits'),
        ('spin', 'max_given', -1, 100000, -1), ('spin', 'max_kept', -1, 100000, -1),
        ('spin', 'max_proofs', -1, 100000, 1), ('spin', 'max_megs', -1, 100000, 200),
        ('spin', 'max_seconds', -1, 100000, 60), ('spin', 'max_minutes', -1, 100000, -1),
        ('spin', 'max_hours', -1, 1000, -1), ('spin', 'max_days', -1, 100, -1),
        ('sub', 'Limits on Kept Clauses'),
        ('spin', 'max_weight', -1000, 100000, 100), ('spin', 'max_depth', -1, 1000, -1),
        ('spin', 'max_literals', -1, 1000, -1), ('spin', 'max_vars', -1, 1000, -1),
        ('sub', 'Sos Control'),
        ('spin', 'sos_limit', -1, 2147483647, 20000)
    ]),
    ("Search Prep", [
        ('flag', 'expand_relational_defs', False), ('flag', 'dont_flip_input', False),
        ('flag', 'process_initial_sos', True), ('flag', 'sort_initial_sos', False),
        ('flag', 'predicate_elim', True), ('spin', 'fold_denial_max', -1, 1000, 0)
    ]),
    ("Goals/Denials", [
        ('flag', 'restrict_denials', False), ('flag', 'reuse_denials', False)
    ]),
    ("Select Given", [
        ('sub', 'Selection Ratio'),
        ('spin', 'hints_part', 0, 2147483647, 2147483647),
        ('spin', 'age_part', 0, 1000, 1),
        ('spin', 'weight_part', 0, 1000, 0),
        ('spin', 'false_part', 0, 1000, 4),
        ('spin', 'true_part', 0, 1000, 4),
        ('spin', 'random_part', 0, 1000, 0),
        ('sub', 'Semantic Guidance'),
        ('combo', 'multiple_interps', ["false_in_all", "false_in_some"], "false_in_all"),
        ('spin', 'eval_limit', -1, 100000, 1024),
        ('sub', 'Meta Options'),
        ('spin', 'pick_given_ratio', -1, 1000, -1),
        ('flag', 'breadth_first', False),
        ('flag', 'lightest_first', False), ('flag', 'random_given', False),
        ('sub', 'Others'),
        ('flag', 'input_sos_first', True), ('flag', 'breadth_first_hints', False)
    ]),
    ("Inference Rules", [
        ('sub', 'Ordinary Rules'),
        ('flag', 'binary_resolution', False), ('flag', 'neg_binary_resolution', False),
        ('flag', 'hyper_resolution', False), ('flag', 'pos_hyper_resolution', False),
        ('flag', 'neg_hyper_resolution', False), ('flag', 'ur_resolution', False),
        ('flag', 'pos_ur_resolution', False), ('flag', 'neg_ur_resolution', False),
        ('flag', 'paramodulation', False),
        ('sub', 'Other Rules'),
        ('spin', 'new_constants', 0, 10000, 0), ('flag', 'factor', False),
        ('sub', 'General Restrictions'),
        ('combo', 'literal_selection', ["max_negative", "all_negative", "none"], "max_negative"),
        ('sub', 'Resolution Restrictions'),
        ('flag', 'ordered_res', True), ('flag', 'check_res_instances', False),
        ('flag', 'initial_nuclei', False), ('spin', 'ur_nucleus_limit', -1, 10000, -1),
        ('sub', 'Paramodulation Restrictions'),
        ('flag', 'ordered_para', True), ('flag', 'check_para_instances', False),
        ('flag', 'para_from_vars', True), ('flag', 'para_units_only', False),
        ('spin', 'para_lit_limit', -1, 10000, -1)
    ]),
    ("Rewriting", [
        ('sub', 'Term Rewriting Limits'),
        ('spin', 'demod_step_limit', -1, 100000, 1000), ('spin', 'demod_size_limit', -1, 100000, 1000),
        ('sub', 'Others'),
        ('flag', 'back_demod', True), ('flag', 'unit_deletion', False), ('flag', 'cac_redundancy', True),
        ('sub', 'Lex-Dependent Rewriting'),
        ('flag', 'lex_dep_demod', True), ('flag', 'lex_dep_demod_sane', True),
        ('spin', 'lex_dep_demod_lim', -1, 10000, 11), ('flag', 'lex_order_vars', False)
    ]),
    ("Weighting", [
        ('sub', 'Symbol Weights'),
        ('spin', 'variable_weight', -1000, 1000, 1), ('spin', 'constant_weight', -1000, 1000, 1),
        ('spin', 'not_weight', -1000, 1000, 0), ('spin', 'or_weight', -1000, 1000, 0),
        ('spin', 'sk_constant_weight', -1000, 1000, 1), ('spin', 'prop_atom_weight', -1000, 1000, 1),
        ('sub', 'Penalties'),
        ('spin', 'skolem_penalty', -1000, 1000, 1), ('spin', 'nest_penalty', -1000, 1000, 0),
        ('spin', 'depth_penalty', -1000, 1000, 0), ('spin', 'var_penalty', -1000, 1000, 0),
        ('sub', 'Others'),
        ('spin', 'default_weight', -1000, 2147483647, 2147483647)
    ]),
    ("Process Inferred", [
        ('flag', 'safe_unit_conflict', False), ('flag', 'back_subsume', True),
        ('spin', 'backsub_check', -1, 100000, 500)
    ]),
    ("Input/Output", [
        ('flag', 'print_initial_clauses', True), ('flag', 'print_given', True),
        ('flag', 'print_gen', False), ('flag', 'print_kept', False),
        ('flag', 'print_labeled', False), ('flag', 'print_proofs', True),
        ('flag', 'print_clause_properties', False),
        ('combo', 'stats', ["none", "some", "lots", "all"], "lots"),
        ('spin', 'report', -1, 100000, -1), ('flag', 'prolog_style_variables', False)
    ]),
    ("Hints", [
        ('flag', 'limit_hint_matchers', False), ('flag', 'collect_hint_labels', False),
        ('flag', 'degrade_hints', True), ('flag', 'back_demod_hints', True)
    ]),
    ("Other Options", [
        ('spin', 'random_seed', -1, 100000, 0)
    ])
]